/*
 * Copyright 2022 Our Stars K.K.,
 * - Noritsuna Imamura <noritsuna.imamura@ourstars.jp>
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(sddc_source.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(00715220c35d8d6ad376932d285e13b4)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <sddc/sddc_source.h>
// pydoc.h is automatically generated in the build directory
#include <sddc_source_pydoc.h>

void bind_sddc_source(py::module& m)
{

    using sddc_source    = gr::sddc::sddc_source;


    py::class_<sddc_source, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<sddc_source>>(m, "sddc_source", D(sddc_source))

        .def(py::init(&sddc_source::make),
           D(sddc_source,make)
        )
        



        ;




}








